### ISSUE TITLE
Could not create New survey v2.1.5

### ISSUE THREAD

**Issue by anusuyab** [phpESP/phpESP#1]
I downloaded Stable version of phpESP 2.1.5 Version. But i cannot create new survey. When i clicke create new survey link, it shows blank page showing only phpESP logo on top left. 
My configuration

> Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3
> Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: f373ea5dd5538761406a8022a4b8a374418b240e $
> PHP extension: mysqli

**Comment by flobee** [comment]
server logs will give you an answer! sorry for that bad delay! Answer: php version too new!
